### ISSUE TITLE
Add a 404 screen for every page that does not exists and we are trying to access it

### ISSUE THREAD

**Issue by chirag35847** [chirag35847/Scholar-Chat#17]

**Comment by chirag35847** [comment]
If you try to access any route which is not defined, there a 404 message must be show like https://github.com/dfdfddsfsdfsdfdsfds

**Comment by kuchiPie** [comment]
Currently on the Scholar chat website, if any other route is tried to access then a strange error message which is 
![image](https://user-images.githubusercontent.com/78674160/201472761-e731fb09-ab16-4766-9292-8c1ce29d96e4.png)
.
Make a special Error page as shown by chirag.

**Comment by KshitizSachan** [comment]
Could this issue be assigned to me ,
Would love to work on it .

**Comment by kuchiPie** [comment]
> Could this issue be assigned to me , Would love to work on it .

We are not going to assign any issue to anyone. If you think you can solve the issue then start working on it on your forked repo and then send a pull request once the feature is developed.

**Comment by kuchiPie** [comment]
Completed by @KshitizSachan
