### ISSUE TITLE
Show errors based on input in react frontend

### ISSUE THREAD

**Issue by kuchiPie** [chirag35847/Scholar-Chat#22]
![image](https://user-images.githubusercontent.com/78674160/201471596-e5b585d6-de5a-4da0-9d26-9815e08943de.png)
Currently, the input tag takes the input of all types (text, numbers, special characters). Also, the input tag expects the user adds hyphens after every 4 digits.

1. The input tag should also add hyphens automatically after every 4 digits in case the user inputs numbers.

**Comment by Xoviec** [comment]
Could you give any info how to setup this app please?

**Comment by AnthonyHad** [comment]
Would be happy to attempt to work on this!

**Comment by KshitizSachan** [comment]
Could this issue be assigned to me ,
Would love to work on it .

**Comment by kuchiPie** [comment]
> Could you give any info how to setup this app please?

```
npm install
nodemon backend/server.js
cd frontend
npm install
npm start
```

**Comment by kuchiPie** [comment]
> Could this issue be assigned to me , Would love to work on it .

We are not going to assign any issue to anyone. If you think you can solve the issue then start working on it on your forked repo and then send a pull request once the feature is developed.

**Comment by kuchiPie** [comment]
Completed by @ashitoshsable
